import MechClasses from "./MechClasses";

export default {
  SmallLaserTurret: {
    fullName: "Small Laser Turret (S1M1L0/HP1)",
    shortName: "SLTurret",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  MGTurret: {
    fullName: "MG Turret (S1M0L0/HP1)",
    shortName: "MGTurret",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  Wasp: {
    fullName: "Wasp",
    shortName: "Wasp",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/3520?skill=4",
  },
  Jenner: {
    fullName: "Jenner",
    shortName: "Jenner",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/1692?skill=4",
  },
  Panther: {
    fullName: "Panther",
    shortName: "Panther",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/2425?skill=4",
  },
  Mercury: {
    fullName: "Mercury",
    shortName: "Mercury",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/4624?skill=4",
  },
  Urban: {
    fullName: "Urban Mech",
    shortName: "Urban",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/3354?skill=4",
  },
  Raven: {
    fullName: "Raven",
    shortName: "Raven",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/2662?skill=4",
  },
  Sentinel: {
    fullName: "Sentinel",
    shortName: "Sentinel",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/2857?skill=4",
  },
  Wolfshound: {
    fullName: "Wolfshound",
    shortName: "Wolfshound",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/3560?skill=4",
  },
  Locust: {
    fullName: "Locust",
    shortName: "Locust",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/1901?skill=4",
  },
  Commando: {
    fullName: "Commando",
    shortName: "Commando",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/670?skill=4",
  },
  LargeLaserTurret: {
    fullName: "Large Laser Turret (S2M2L0/HP1)",
    shortName: "LLTurret",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  LRM10Turret: {
    fullName: "Long Range Missile 10 Turret (S0M1L2/HP2)",
    shortName: "LRM10Turret",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Wolverine: {
    fullName: "Wolverine",
    shortName: "Wolverine",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/3573?skill=4",
  },
  Hatchetman: {
    fullName: "Hatchetman",
    shortName: "Hatchetman",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/1410?skill=4",
  },
  Hunchback: {
    fullName: "Hunchback",
    shortName: "Hunchback",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/1561?skill=4",
  },
  Enforcer: {
    fullName: "Enforcer",
    shortName: "Enforcer",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/976?skill=4",
  },
  Centurion: {
    fullName: "Centurion",
    shortName: "Centurion",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/516?skill=4",
  },
  ShadowHawk: {
    fullName: "Shadow Hawk",
    shortName: "Shadow Hawk",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/2901?skill=4",
  },
  Blackjack: {
    fullName: "Blackjack",
    shortName: "Blackjack",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/373?skill=4",
  },
  PhoenixHawk: {
    fullName: "Phoenix Hawk",
    shortName: "Phoenix Hawk",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/2491?skill=4",
  },
  Griffin: {
    fullName: "Griffin",
    shortName: "Griffin",
    mechClass: MechClasses[2],
    cardUrl: "http://masterunitlist.info/Unit/Card/1297?skill=4",
  },
  LRM20Turret: {
    fullName: "Long Range Missile 20 Turret (S0M2L3/HP2)",
    shortName: "LRM20Turret",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  PPCTurret: {
    fullName: "PPC Turret (S3M3L3/HP2)",
    shortName: "PPCTurret",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Orion: {
    fullName: "Orion",
    shortName: "Orion",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/2334?skill=4",
  },
  Catapult: {
    fullName: "Catapult",
    shortName: "Catapult",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/478?skill=4",
  },
  Exterminator: {
    fullName: "Exterminator",
    shortName: "Exterminator",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/4147?skill=4",
  },
  Warhammer: {
    fullName: "Warhammer",
    shortName: "Warhammer",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/3488?skill=4",
  },
  Crusader: {
    fullName: "Crusader",
    shortName: "Crusader",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/752?skill=4",
  },
  Rifleman: {
    fullName: "Rifleman",
    shortName: "Rifleman",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/2697?skill=4",
  },
  Grashopper: {
    fullName: "Grashopper",
    shortName: "Grashopper",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/1268?skill=4",
  },
  BlackKnight: {
    fullName: "Black Knight",
    shortName: "BlackKnight",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/358?skill=4",
  },
  Thunderbolt: {
    fullName: "Thunderbolt",
    shortName: "Thunderbolt",
    mechClass: MechClasses[3],
    cardUrl: "http://masterunitlist.info/Unit/Card/3240?skill=4",
  },
  DoublePPCTurret: {
    fullName: "Double PPC Turret (S4M4L4/HP2)",
    shortName: "DPPCTurret",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  LRM40Turret: {
    fullName: "Long Range Missile 40 Turret (S0M3L4/HP2)",
    shortName: "LRM40Turret",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Atlas: {
    fullName: "Atlas",
    shortName: "Atlas",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/144?skill=4",
  },
  KingCrab: {
    fullName: "King Crab",
    shortName: "King Crab",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/1770?skill=4",
  },
  Banshee: {
    fullName: "Banshee",
    shortName: "Banshee",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/247?skill=4",
  },
  Highlander: {
    fullName: "Highlander",
    shortName: "Highlander",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/1517?skill=4",
  },
  Awesome: {
    fullName: "Awesome",
    shortName: "Awesome",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/174?skill=4",
  },
  Battlemaster: {
    fullName: "Battlemaster",
    shortName: "Battlemaster",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/294?skill=4",
  },
  Victor: {
    fullName: "Victor",
    shortName: "Victor",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/3409?skill=4",
  },
  Marauder2: {
    fullName: "MarauderII",
    shortName: "MarauderII",
    mechClass: MechClasses[4],
    cardUrl: "http://masterunitlist.info/Unit/Card/2059?skill=4",
  },
};
