import MechClasses from "./MechClasses";

export default {
  SmallLaserTurret: {
    fullName: "Small Laser Turret (S1M1L0/HP2)",
    shortName: "SLTurret",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  MGTurret: {
    fullName: "MG Turret (S1M0L0/HP2)",
    shortName: "SLTurret",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  Wasp: {
    fullName: "Wasp",
    shortName: "Wasp",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/3528?skill=4",
  },
  Jenner: {
    fullName: "Jenner",
    shortName: "Jenner",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/1687?skill=4",
  },
  Panther: {
    fullName: "Panther",
    shortName: "Panther",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/2422?skill=4",
  },
  Mercury: {
    fullName: "Mercury",
    shortName: "Mercury",
    mechClass: MechClasses[1],
    cardUrl: "http://masterunitlist.info/Unit/Card/4624?skill=4",
  },
  Urban: {
    fullName: "Urban Mech",
    shortName: "Urban",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  Raven: {
    fullName: "Raven",
    shortName: "Raven",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  Sentinel: {
    fullName: "Sentinel",
    shortName: "Sentinel",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  Wolfshound: {
    fullName: "Wolfshound",
    shortName: "Wolfshound",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  Locust: {
    fullName: "Locust",
    shortName: "Locust",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  Commando: {
    fullName: "Commando",
    shortName: "Commando",
    mechClass: MechClasses[1],
    cardUrl: "",
  },
  LargeLaserTurret: {
    fullName: "Small Laser Turret (S2M2L0/HP2)",
    shortName: "LLTurret",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  LRM10Turret: {
    fullName: "Long Range Missile 10 Turret (S0M2L2/HP2)",
    shortName: "LRM10Turret",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Wolverine: {
    fullName: "Wolverine",
    shortName: "Wolverine",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Hatchetman: {
    fullName: "Hatchetman",
    shortName: "Hatchetman",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Hunchback: {
    fullName: "Hunchback",
    shortName: "Hunchback",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Enforcer: {
    fullName: "Enforcer",
    shortName: "Enforcer",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Centurion: {
    fullName: "Centurion",
    shortName: "Centurion",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  ShadowHawk: {
    fullName: "ShadowHawk",
    shortName: "ShadowHawk",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Blackjack: {
    fullName: "Blackjack",
    shortName: "Blackjack",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  PhoenixHawk: {
    fullName: "PhoenixHawk",
    shortName: "PhoenixHawk",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  Griffin: {
    fullName: "Griffin",
    shortName: "Griffin",
    mechClass: MechClasses[2],
    cardUrl: "",
  },
  LRM20Turret: {
    fullName: "Long Range Missile 20 Turret (S0M3L3/HP2)",
    shortName: "LRM20Turret",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  PPGTurret: {
    fullName: "PPG Turret (S3M3L3/HP2)",
    shortName: "PPGTurret",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Orion: {
    fullName: "Orion",
    shortName: "Orion",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Catapult: {
    fullName: "Catapult",
    shortName: "Catapult",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Exterminator: {
    fullName: "Exterminator",
    shortName: "Exterminator",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Warhammer: {
    fullName: "Warhammer",
    shortName: "Warhammer",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Crusader: {
    fullName: "Crusader",
    shortName: "Crusader",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Rifleman: {
    fullName: "Rifleman",
    shortName: "Rifleman",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Grashopper: {
    fullName: "Grashopper",
    shortName: "Grashopper",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  BlackKnight: {
    fullName: "Black Knight",
    shortName: "BlackKnight",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  Thunderbolt: {
    fullName: "Thunderbolt",
    shortName: "Thunderbolt",
    mechClass: MechClasses[3],
    cardUrl: "",
  },
  DoublePPGTurret: {
    fullName: "Double PPG Turret (S4M4L4/HP2)",
    shortName: "DPPGTurret",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  LRM40Turret: {
    fullName: "Long Range Missile 40 Turret (S0M4L4/HP2)",
    shortName: "LRM40Turret",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Atlas: {
    fullName: "Atlas",
    shortName: "Atlas",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  KingCrab: {
    fullName: "KingCrab",
    shortName: "KingCrab",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Banshee: {
    fullName: "Banshee",
    shortName: "Banshee",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Highlander: {
    fullName: "Highlander",
    shortName: "Highlander",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Awesome: {
    fullName: "Awesome",
    shortName: "Awesome",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Battlemaster: {
    fullName: "Battlemaster",
    shortName: "Battlemaster",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Victor: {
    fullName: "Victor",
    shortName: "Victor",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
  Marauder2: {
    fullName: "MarauderII",
    shortName: "MarauderII",
    mechClass: MechClasses[4],
    cardUrl: "",
  },
};
